[package]
name = "crm"
version = "0.1.0"
edition = "2021"
authors = ["Shane Poppleton <shane@bjja.com.au>"]
license = "GPL-3.0-or-later"


[dependencies]
clap = {  version = "4.4.8" , features = ["derive"]}
crossterm = "0.27.0"
directories = "5.0.1"
log = "0.4.20"
simplelog = "0.12.1"
